model: ollama
stream: true
keybindings: vi
editor: nvim
wrap: auto
wrap_code: true
highlight: true
light_theme: true
clients:
  - type: openai
    api_base: https://api.openai.com/v1
    api_key: xxx
    organization_id: xxx
  - type: claude
    api_base: https://api.anthropic.com/v1
    api_key: xxx
  - type: openai-compatible
    name: groq
    api_base: https://api.groq.com/openai/v1
    api_key: xxx
  - type: openai-compatible
    name: ollama
    api_base: http://127.0.0.1:11434/v1
    api_key: ollama
    models:
      - name: phi3.5:latest
        supports_vision: false
        supports_function_calling: false
      - name: qwen2:1.5b-instruct-q8_0
        supports_vision: false
        supports_function_calling: false
      - name: gemma2:2b-instruct-q8_0
        supports_vision: false
        supports_function_calling: false
