#!/bin/bash

GTPDIR="$HOME/.gconf/apps/"

rm -rf ~/{.R,.Rprofile,.bashrc,.gitignore,.gitconfig,.gvimrc,.inputrc,.screenrc,.vim,.vimrc,scripts,.tmux.conf,.crclient,.bash_profile}
rm -rf "$GTPDIR/gnome-terminal"

mkdir -p "$GTPDIR"

ln -s $PWD/R ~/.R
ln -s $PWD/Rprofile ~/.Rprofile
ln -s $PWD/bashrc ~/.bashrc
ln -s $PWD/bash_profile ~/.bash_profile
ln -s $PWD/gitignore ~/.gitignore
ln -s $PWD/gitconfig ~/.gitconfig
ln -s $PWD/gvimrc ~/.gvimrc
ln -s $PWD/inputrc ~/.inputrc
ln -s $PWD/screenrc ~/.screenrc
ln -s $PWD/vim ~/.vim
ln -s $PWD/vimrc ~/.vimrc
ln -s $PWD/tmux.conf ~/.tmux.conf
ln -s $PWD/crclient ~/.crclient
ln -s $PWD/scripts ~/scripts
ln -s $PWD/gnome-terminal ~/.gconf/apps/

exit 0
