'use strict';
const {test}=require('node:test');const assert=require('node:assert/strict');
const fs=require('node:fs');const os=require('node:os');const path=require('node:path');
const {prepare,finish}=require('../scripts/bridge.cjs');
function fixture(t){const dir=fs.mkdtempSync(path.join(os.tmpdir(),'fal-ms-365-test-'));t.after(()=>fs.rmSync(dir,{recursive:true,force:true}));return dir;}
test('Unicode and quotes survive request JSON; private mode',t=>{const dir=fixture(t),src=path.join(dir,'in.json'),dst=path.join(dir,'out.json');const r={operation:'mail',action:'send',body:'“Graph” & café\nO\'Brien',approved:false};fs.writeFileSync(src,JSON.stringify(r));prepare(src,dst);assert.deepEqual(JSON.parse(fs.readFileSync(dst,'utf8').replace(/^\uFEFF/,'')),r);assert.equal(fs.statSync(dst).mode&0o777,0o600);});
test('relative output directory rejected',t=>{const dir=fixture(t),src=path.join(dir,'in.json');fs.writeFileSync(src,JSON.stringify({operation:'mail',action:'export',outputDir:'../out'}));assert.throws(()=>prepare(src,path.join(dir,'out.json')),/absolute/);});
test('non-object request rejected',t=>{const dir=fixture(t),src=path.join(dir,'in.json');fs.writeFileSync(src,'[]');assert.throws(()=>prepare(src,path.join(dir,'out.json')),/object/);});
test('non-export results pass through unchanged',t=>{const dir=fixture(t),src=path.join(dir,'in.json'),result=path.join(dir,'result.json');fs.writeFileSync(src,'{}');fs.writeFileSync(result,JSON.stringify({status:'error',error:'denied'}));assert.deepEqual(finish(src,result),{status:'error',error:'denied'});});
test('all example JSON files parse; write examples unapproved',()=>{const dir=path.join(__dirname,'../examples');for(const name of fs.readdirSync(dir).filter(n=>n.endsWith('.json'))){const r=JSON.parse(fs.readFileSync(path.join(dir,name),'utf8'));assert.ok(r.operation&&r.action);if(/send|save-draft|create-invite/.test(r.action))assert.equal(r.approved,false);}});
test('relative Markdown references resolve inside bundle',()=>{const root=path.resolve(__dirname,'..');function walk(dir){for(const n of fs.readdirSync(dir)){const p=path.join(dir,n);if(fs.statSync(p).isDirectory())walk(p);else if(p.endsWith('.md')){const text=fs.readFileSync(p,'utf8');for(const m of text.matchAll(/\]\(([^)]+)\)/g)){const target=m[1];if(!/^(https?:|#)/.test(target))assert.ok(fs.existsSync(path.resolve(dir,target.split('#')[0])),`${p}: ${target}`);}}}}walk(root);});
const {execFileSync}=require('node:child_process');
function exportFixture(t, artifacts){const dir=fixture(t),stage=path.join(dir,'stage'),out=path.join(dir,'out');fs.mkdirSync(stage);const request=path.join(dir,'request.json'),result=path.join(dir,'result.json');fs.writeFileSync(request,JSON.stringify({outputDir:out}));const win=execFileSync('wslpath',['-w',stage],{encoding:'utf8'}).trim();fs.writeFileSync(result,JSON.stringify({status:'ok',stagingWindowsDirectory:win,artifacts}));return {stage,out,request,result};}
test('HTML, attachments and companion assets copy with integrity/private modes',t=>{const f=exportFixture(t,[{name:'message.html'},{name:'message_files'},{name:'attachment.pdf'}]);fs.writeFileSync(path.join(f.stage,'message.html'),'<html>hello</html>');fs.writeFileSync(path.join(f.stage,'attachment.pdf'),'dummy-pdf');fs.mkdirSync(path.join(f.stage,'message_files'));fs.writeFileSync(path.join(f.stage,'message_files','asset.xml'),'asset');const result=finish(f.request,f.result);assert.ok(result.artifacts.every(a=>a.verified));assert.equal(fs.statSync(path.join(f.out,'message.html')).mode&0o777,0o600);assert.equal(fs.statSync(path.join(f.out,'message_files')).mode&0o777,0o700);assert.equal(fs.readFileSync(path.join(f.out,'message_files','asset.xml'),'utf8'),'asset');assert.ok(result.artifacts[0].sha256);assert.ok(!fs.existsSync(f.stage));});
test('existing destination blocks overwrite and preserves staging',t=>{const f=exportFixture(t,[{name:'file.txt'}]);fs.writeFileSync(path.join(f.stage,'file.txt'),'new');fs.mkdirSync(f.out);fs.writeFileSync(path.join(f.out,'file.txt'),'old');assert.throws(()=>finish(f.request,f.result),/overwrite/);assert.equal(fs.readFileSync(path.join(f.out,'file.txt'),'utf8'),'old');assert.ok(fs.existsSync(f.stage));});
test('artifact path traversal rejected',t=>{const f=exportFixture(t,[{name:'../secret.txt'}]);assert.throws(()=>finish(f.request,f.result),/Unsafe/);});
test('symlink source artifact rejected',t=>{const f=exportFixture(t,[{name:'link.txt'}]);fs.writeFileSync(path.join(f.stage,'source.txt'),'source');fs.symlinkSync('source.txt',path.join(f.stage,'link.txt'));assert.throws(()=>finish(f.request,f.result),/Symlink/);});
