#!/bin/bash

function beef_up()
{
  sudo /etc/rc.d/autofs start
  sudo /etc/rc.d/cupsd start
  sudo /etc/rc.d/bluetooth start
  sudo cpufreq-set -r --governor performance
  sleep 1
  cpufreq-info | grep current | sort -u
}

if [[ "$1" == "-n" ]]; then
  beef_up
else
  beef_up
  sudo /etc/rc.d/networkmanager start
fi

exit 0
