#!/bin/bash

if [[ "$1" == "--tor" ]]; then
  shift
  /usr/bin/chromium --user-data-dir='/tmp/chromium-tor' --incognito --enable-seccomp-sandbox --proxy-server='socks://localhost:9050' check.torproject.org "$@" &> /dev/null &
else
  /usr/bin/chromium --enable-seccomp-sandbox "$@" &> /dev/null &
fi

exit 0
