#!/bin/bash

OIFS=$IFS
IFS=$'\n'

if [ -z "$1" ]
then
  echo
  echo "No input provided. The script is exiting."

  IFS=$OIFS
  unset OIFS
  exit 0

else
  for d in $*
  do
    if ! [ -e "$d" ]
    then
      echo
      echo "The file "$d" does not exist."
    else
      FPATH=$(readlink -m $(dirname "$d"))
      NAME=$(basename "$d")
      NEW_NAME=$(echo "$NAME" | tr [:upper:] [:lower:])
      if [ -e "$FPATH"/"$NEW_NAME" ]
      then
        echo
        echo "File $NEW_NAME exists."
        echo "No changes made to $d."
      else
        mv "$FPATH"/"$NAME" "$FPATH"/"$NEW_NAME"
      fi
    fi
  done

  IFS=$OIFS
  unset OIFS
  exit 0

fi
