#!/bin/bash

echo "Please turn on the wi-fi hardware switch if any before proceeding."
read && sleep 2s

echo "The present maps of the interfaces are:

HWAddress         Interface
$(ifconfig | grep HWaddr | awk '{print $5, $1}')"

echo "
Guessing the name of the wireless interface: $(iwconfig 2> /dev/null | 
grep ESSID | awk '{print $1}')"

INTFS=$(ifconfig | grep HWaddr | awk '{print $1}')

echo "Give desired names for the two interfaces in the order: $INTFS"
read names1
read names1

#if [ -e /etc/udev/rules.d/10-network.rules ]
#then
#gvim /etc/udev/rules.d/10-network.rules
#echo "Please make sure the file contains the following lines:"
#echo 'SUBSYSTEM=="net", ATTR{address}=="00:21:70:C3:EB:DA", NAME="eth0"'
#echo 'SUBSYSTEM=="net", ATTR{address}=="00:23:4D:D5:4F:0B", NAME="wlan0"'
#read
#echo "The interfaces shall be renamed upon reboot."
#exit 0
#else
#echo '
#SUBSYSTEM=="net", ATTR{address}=="00:21:70:C3:EB:DA", NAME="lan0"
#SUBSYSTEM=="net", ATTR{address}=="00:23:4D:D5:4F:0B", NAME="wlan0"
#' > /etc/udev/rules.d/10-network.rules
#echo "The interfaces shall be renamed upon reboot."
#exit 0
#fi

exit 0
