#!/bin/bash

PID=$(ps x | grep libflashplayer.so | grep -v grep | awk '{print $1}')

if [ "$PID" = "" ]
then
  echo "libflashplayer is not being accessed. No flash file streaming."
  exit 0
else
  for ID in $PID
  do
    FDS=$(lsof -p "$ID" | grep "/tmp/Flash" | awk '{print $4}')
    for d in $FDS
    do
      FILENAME=$(lsof -p "$ID" | grep "/tmp/Flash" | grep "$d" | awk '{print $9}' | cut -f 3 -d '/')
      FD=${d:0:2}
      mplayer -idx -fs -stop-xscreensaver  /proc/"$ID"/fd/"$FD" < /dev/null &> /dev/null
    done
  done
  exit 0
fi
