#!/bin/bash

#########################

#TODO: Extend the script to handle all sorts of R packages besides only tar.gz packages.

#########################

LIBDIR="$HOME"/rstat/pkgs/src/contrib
ARCDIR="$HOME"/rstat/pkgs/src/contrib/archive
REPO='http://cran.revolution-computing.com/src/contrib/'

#########################

if ! [ -d "$ARCDIR" ]
then
  mkdir -v "$ARCDIR"
fi

#########################

if [ -e "$LIBDIR"/index.html ]
then 
  rm "$LIBDIR"/index.html
fi

if [ -e "$LIBDIR"/PACKAGES ]
then 
  rm "$LIBDIR"/PACKAGES
fi

wget --directory-prefix="$LIBDIR" "$REPO"
wget --directory-prefix="$LIBDIR" "$REPO"PACKAGES

cd "$LIBDIR"
ls *tar.gz > oldpkglist.txt
grep 'tar\.gz' "$LIBDIR"/index.html | cut -f 6 -d '"' > newpkglist.txt

for PKG in $(cat oldpkglist.txt)
do
  PKGNAME=$(echo "$PKG" | cut -f 1 -d '_')_
  NEWPKG=$(grep ^"$PKGNAME" newpkglist.txt)
  if [[ "$NEWPKG" > "$PKG" ]]
  then
    echo "There is a new version "$NEWPKG""
    wget --continue --directory-prefix="$LIBDIR" "$REPO""$NEWPKG"
    mv "$PKG" "$ARCDIR"
  fi
done

rm oldpkglist.txt newpkglist.txt

exit 0

#########################
