#!/bin/bash

#########################

LIBDIR="$HOME"/rstat/pkgs/src/contrib
ARCDIR="$HOME"/rstat/pkgs/src/contrib/archive
REPO='http://cran.revolution-computing.com/src/contrib/'
PKGLIST=/tmp/pkglist.txt

#########################

if [ -z "$1" ]
then
  echo "No package names supplied. The script is exiting."
  exit 1
else
  grep -e 'tar\.gz' "$LIBDIR"/index.html | cut -f 6 -d '"' > "$PKGLIST"

  for PKG in $*
  do
    PKGVER=$(grep -e ^"$PKG"_ "$PKGLIST")
    wget --continue --directory-prefix="$LIBDIR" "$REPO""$PKGVER"
  done
fi
