#!/bin/bash

#########################

REPO=file://"$HOME"/rstat/pkgs
LIBDIR="$HOME"/rstat/pkgs/src/contrib
LOGDIR=/var/log/rpkg_install_$(date +%d%m%y_%H%M%S)

if [ -d /var/log/rpkg_install_* ]
then
  rm -rf /var/log/rpkg_install_*
fi

mkdir "$LOGDIR"

#########################

PKGLIST="$LOGDIR"/pkglist.txt
EVENTLOG="$LOGDIR"/events.txt

#########################

ls "$LIBDIR"/*tar.gz | cut -f 7 -d '/' | cut -f 1 -d '_' > "$PKGLIST"

echo "Depending on the number and size of packages being upgraded, this can
take some time. Please keep patience."
echo ""

TOTAL=$(wc -l "$PKGLIST" | awk '{print $1}')
COUNTER=1

for PKG in $(cat "$PKGLIST")
do
  REMAINING=$(($TOTAL-$COUNTER))
  echo "Processing package \"$PKG\". "$REMAINING" more to go."
  if [ -d /usr/lib/R/library/"$PKG" ]
  then
    NEWPKGVER=$(ls "$LIBDIR" | grep ^"$PKG"_ | cut -f 7 -d '/' | cut -f 2 -d ' ' | tr -d -c [0-9])
    OLDPKGVER=$(grep -e Version /usr/lib/R/library/"$PKG"/DESCRIPTION | awk '{print $2}' | tr -d -c [0-9])
    if [ $NEWPKGVER -gt $OLDPKGVER ]
    then
      echo "install.packages(\"$PKG\", repos=\"$REPO\")" | R --slave &>> "$EVENTLOG"
    fi
  else
    echo "install.packages(\"$PKG\", repos=\"$REPO\")" | R --slave &>> "$EVENTLOG"
  fi
  let COUNTER+=1
done

echo ""
echo -e "\E[34;1m$(grep -i -e DONE "$EVENTLOG" | sort -u)"
echo ""
echo -e "\E[31;1m$(grep -i -e ERROR "$EVENTLOG" | sort -u)"

exit 0

#########################
