#!/bin/bash

OIFS="$IFS"
IFS=$'\n'

if [ -z "$1" ]; then
  echo "No input provided. The script is exiting."
  IFS=$OIFS
  unset OIFS
  exit 0
fi

for d in $*
do
  if ! [ -e "$d" ]; then
    echo "The file "$d" does not exist."
  else
    FPATH=$(readlink -m $(dirname "$d"))
    EXT=$(getext "$d")
    NAME=$(basename "$d" $EXT)
    NEW_NAME=$(echo "$NAME" | tr -c [:alnum:] - | tr [:upper:] [:lower:] | sed 's:-\{2,\}:-:g; s:^-::g; s:-$::g')
    if [ -e "$FPATH"/"$NEW_NAME" ]; then
      echo "File $NEW_NAME exists."
      echo "No changes made to $d."
    else
      mv "$FPATH"/"$NAME"$EXT "$FPATH"/"$NEW_NAME"$EXT
    fi
  fi
done
IFS=$OIFS
unset OIFS
exit 0
