#!/bin/bash

/usr/bin/syndaemon -k -i 0.5 -d &

/usr/bin/artha &

devilspie &> /dev/null &

/usr/local/bin/quake &

sleep 1s && zenity --info \
  --title 'Fortune cookie for the cookie monster!' \
  --text "$(fortune -s)"

if [[ $(hostname) == "ArchWizard" ]]; then
  /usr/bin/synclient TouchpadOff=1 &
  sudo su -c 'echo -n 50 > /sys/devices/platform/i8042/serio1/serio2/speed'
  sudo su -c 'echo -n 255 > /sys/devices/platform/i8042/serio1/serio2/sensitivity'
fi

exit 0
