#!/bin/bash

pkill batterymon; /usr/local/bin/batterymon &
/usr/bin/synclient TouchpadOff=1 &
/usr/bin/setxkbmap -option caps:swapescape
/usr/bin/artha &
sudo su -c 'echo -n 100 > /sys/devices/platform/i8042/serio1/serio2/speed'
sudo su -c 'echo -n 255 > /sys/devices/platform/i8042/serio1/serio2/sensitivity'

sleep 1s && zenity --info \
  --title 'Fortune cookie for the cookie monster!' \
  --text "$(fortune -a)"

exit 0
