#!/bin/bash

pkill batterymon; /usr/local/bin/batterymon &
/usr/bin/synclient TouchpadOff=1 &
/usr/bin/setxkbmap -option caps:swapescape
/usr/bin/artha &
/usr/bin/gnome-terminal &

sleep 1s && zenity --info \
  --title 'Fortune cookie for the cookie monster!' \
  --text "$(fortune -a)"

exit 0
