#!/bin/bash

sudo -u akhilsbehl /usr/local/bin/add-xhost
/usr/local/bin/distwtype &
trayer --expand true --transparent true --alpha 255 --edge bottom \
  --align right --expand true --SetDockType true --widthtype request &
/usr/bin/conky -c "$HOME"/.conkyrc/conky_launchpad &
/usr/bin/artha &
/usr/bin/gnome-terminal

exit 0
