#!/bin/bash

LOGDIR="$HOME"/.log
LOGFILE="$LOGDIR"/batterymon.log
LOGTIME="[$(date +"%d %b; %H:%M:%S")]"

BATSTATUS=$(acpi -b | cut -f 4 -d ' ' | tr -dc '[0-9]')
CHGSTATUS=$(acpi -a | cut -f 3 -d ' ')

ALARM_HIGH_HEAD="Battery Charged"
ALARM_HIGH_BODY="Time to switch off the external power source."

ALARM_LOW_HEAD="Battery Low"
ALARM_LOW_BODY="Time to switch in to external power source."

raise_alarm () {
  DISPLAY="$DISPLAY" notify-send "$1" "$2"
  echo "$LOGTIME" "$1" "$2" >> "$LOGFILE"
}

main () {
  if [[ "$1" -lt "40" && "$2" == "off-line" ]]; then
    raise_alarm "$ALARM_LOW_HEAD" "$ALARM_LOW_BODY"
  elif [[ "$1" -gt "80" && "$2" == "on-line" ]]; then
    raise_alarm "$ALARM_HIGH_HEAD" "$ALARM_HIGH_BODY"
  fi
}

if ! [[ -e "$LOGDIR" ]]; then
  mkdir -p "$LOGDIR"
fi
main "$BATSTATUS" "$CHGSTATUS"

exit 0
