#!/bin/bash

if [[ -z "$1" ]]; then
  echo "Usage: ./$0 file-1.pdf [file-2.pdf ... file-n.pdf] combinedfile.pdf"
  exit 1
fi

## These will only work with bash (>= 3.0)
INFILES="${*: 1:$(($#-1))}" # Go from arg 1 to penultimate.
OUTFILE="${*: -1}" # Pick the last one out.

gs -q \
  -sDEVICE=pdfwrite \
  -dCompatibilityLevel=1.4 \
  -dBATCH \
  -dNOPAUSE \
  -dQUIET \
  -sOutputFile="$OUTFILE" \
  $INFILES

exit 0
