#!/usr/bin/env bash

CURRENT_DIR="$(dirname ${BASH_SOURCE[0]})"

export EDITOR="vim"
cd "$HOME/.lispinstalls/cl-repl/"

sbcl \
    --eval "(ql:quickload :cl-repl)" \
    --eval "(sb-posix:chdir \"$CURRENT_DIR\")" \
    --eval "(cl-repl:main)"

exit 0
