#!/bin/bash

DIR="$1"

if [[ -z "$1" ]]; then
  DIR="$PWD"
fi

find "$DIR" -maxdepth 1 \
  \( -name '*log' -o -name '*nav' -o -name '*out' -o -name '*snm' \
  -o -name '*toc' -o -name '*blg' -o -name '*bbl' -o -name '*vrb' \
  -o -name '*aux' \) \
  -exec rm -v {} \;

exit 0
