#!/bin/bash

NCOL=$(head -1 "$1" | tr -dc $2 | wc -c)
NCOL=$((NCOL+2))

for (( d = 1; d < $NCOL; d++ )); do
  cut -f $d -d $2 "$1" > /tmp/file.txt
  NAME="$(head -n 1 /tmp/file.txt)"
  mv /tmp/file.txt "$1"-"$NAME"
done

exit 0
