#!/bin/bash

ISOPEN=$(wmctrl -l | grep Firefox$)
if [[ -z $ISOPEN ]]; then
  firefox &&
    wmctrl -r 'Firefox' -b add,maximized_vert,maximized_horz &&
    wmctrl -a 'Firefox'
fi

ISFOCUSED=$(xdotool getwindowname $(xdotool getwindowfocus) | awk '{print $NF}')
if [[ $ISFOCUSED != "Firefox" ]]; then
  wmctrl -r 'Firefox' -b remove,below
  wmctrl -R 'Firefox'
fi

exit 0
