#!/bin/bash

OIFS="$IFS"
IFS=$'\n'

DOTS=$(echo "$1" | tr -dc '.')

if [[ -d "$1" || "$DOTS" == "" ]]; then
  EXT=""
else
  EXT=.$(echo "$1" | awk -F '.' '{print $NF}')
fi
echo "$EXT"

IFS=$OIFS
unset OIFS

exit 0
