#!/bin/bash

ARCHIVEDIR="$HOME"/diary
YEAR=$(date +%Y)
MONTH=$(date +%B | tr '[:upper:]' '[:lower:]')
DAY=$(date +%d-%B-%Y | tr '[:upper:]' '[:lower:]')
LONGDAY=$(date +"%A, %d %B, %Y")
TIME=$(date +%r)
ENTRY="$ARCHIVEDIR"/"$YEAR"/"$MONTH"/"$DAY".txt
SWPFILE="$ARCHIVEDIR"/"$YEAR"/"$MONTH"/."$DAY".txt.sw*

if ! [ -e "$ARCHIVEDIR"/"$YEAR"/"$MONTH" ]
then
  mkdir -pv "$ARCHIVEDIR"/"$YEAR"/"$MONTH"
fi

if ! [ -e "$ENTRY" ]
then
  echo "$LONGDAY" > "$ENTRY"
  echo -e "\n##############\n$TIME\n##############" >> "$ENTRY"
  gvim + "$ENTRY"
  exit 0
else
  if [ -e $SWPFILE ]
  then
    echo "A swap file exists. Continuing session."
    echo "Commit changes and call again for a new session."
    gvim + -r "$ENTRY"
    exit 0
  else
    echo -e "\n##############\n$TIME\n##############" >> "$ENTRY"
    gvim + "$ENTRY"
    exit 0
  fi
fi
