#!/bin/bash

OIFS="$IFS"
IFS=$'\n'

for d in $*
do
  FPATH=$(dirname "$d")
  EXT=$(getext "$d")
  NAME=$(basename "$d" $EXT)
  NEWNAME=$(echo "$NAME" | sed 's:^[0-9]\{1,\}::g; s:^-\{1,\}::g')
  if [[ ! -e "$FPATH"/"$NEWNAME"$EXT ]]; then
    mv -n "$FPATH"/"$NAME"$EXT "$FPATH"/"$NEWNAME"$EXT
  else
    echo "$FPATH/$NEWNAME$EXT exists."
  fi
done

IFS=$OIFS
unset OIFS

exit 0
