#!/bin/bash

OIFS="$IFS"
IFS=$'\n'

TMPFILE=/tmp/pdfname$RANDOM.txt

for d in $*; do
  if [[ ! -e "$d" ]]; then
    echo "$d does not exist."
    IFS=$OIFS
    unset OIFS
    exit 1
  fi
  FPATH=$(dirname "$d")
  NAME=$(basename "$d")
  NEWNAME=$( \
    pdfinfo "$d" | grep -e Author -e Title | tac | \
    awk '
      BEGIN {ORS=" "}
      {for (i = 2; i <= NF; i++) print $i}'
  )
  NEWNAME=$( \
    echo "$NEWNAME" | \
    tr -c '[:alnum:]' - | \
    tr '[:upper:]' '[:lower:]' | \
    sed 's:-\{2,\}:-:g; s:^-::g; s:-$::g'
  )
  echo
  echo "$d -> $NEWNAME.pdf"
  CONSENT=""
  while [[ ! ( \
    $CONSENT == "y" || \
    $CONSENT == "n" || \
    $CONSENT == "c" \
    ) ]]; do
    echo "Accept? (y/n/c)"
    read -r CONSENT
  done
  if [[ $CONSENT == "y" ]]; then
    mv -i -v "$d" "$FPATH/$NEWNAME".pdf
  elif [[ $CONSENT == "n" ]]; then
    echo "$NEWNAME".pdf > $TMPFILE
    echo "$NAME" >> $TMPFILE
    xdg-open "$d" &
    xdg-open $TMPFILE
    read
    NEWNAME="$(head -1 $TMPFILE)"
    mv -i -v "$d" "$FPATH/$NEWNAME"
  else
    continue
  fi
done

IFS=$OIFS
unset OIFS

exit 0
