#!/bin/bash

artha &

$HOME/scripts/randomize-wallpaper

sleep 1s && zenity --info \
  --title 'Fortune cookie for the cookie monster!' \
  --text "$(fortune -s)"

if [[ $(hostname) == "ArchWizard" ]]; then
  synclient TouchpadOff=1 &
  sudo su -c 'echo -n 50 > /sys/devices/platform/i8042/serio1/serio2/speed'
  sudo su -c 'echo -n 255 > /sys/devices/platform/i8042/serio1/serio2/sensitivity'
fi

emacs --daemon # If there already is a daemon this will just fail. 

exit 0
