#!/bin/bash

ISOPEN=$(wmctrl -l | grep 'Google Chrome$')
if [[ -z $ISOPEN ]]; then
  google-chrome-stable %U --password-store=basic &&
    wmctrl -r 'Google Chrome' -b add,maximized_vert,maximized_horz &&
    wmctrl -a 'Google Chrome'
fi

ISFOCUSED=$(xdotool getwindowname $(xdotool getwindowfocus) | awk '{print $NF}')
if [[ $ISFOCUSED != 'Google Chrome' ]]; then
  wmctrl -r 'Google Chrome' -b remove,below
  wmctrl -R 'Google Chrome'
fi

exit 0
