#!/bin/bash

ISOPEN=$(wmctrl -l | grep ArchWizard$)
if [[ -z $ISOPEN ]]; then
  roxterm -f -p 'ArchWizard' -d "/home/$(whoami)/tmp" &&
    wmctrl -r 'ArchWizard' -b add,fullscreen &&
    wmctrl -a 'ArchWizard'
fi

ISFOCUSED=$(xdotool getwindowname $(xdotool getwindowfocus))
if [[ $ISFOCUSED != "ArchWizard" ]]; then
  wmctrl -r 'ArchWizard' -b remove,below
  wmctrl -R 'ArchWizard'
else
  wmctrl -r 'ArchWizard' -b add,below
fi

exit 0
