#!/bin/bash

stjerm \
  -ab true \
  -ah true \
  -bg FFFFFF \
  -bell false \
  -b none \
  -fn 'Monaco 10' \
  -fg 000000 \
  -h 768 \
  -k return \
  -km alt \
  -m alt \
  -o 100 \
  -p bottom \
  -st one \
  -tf true \
  -tl '#' \
  -tp top \
  -w 1366 \
  -uc black \
  -cb on \
  -cs block &

exit 0
