#!/bin/bash

extensions=(
    7z
    avi
    bmp
    csv
    doc
    docx
    gif
    gz
    html
    iso
    jpeg
    jpg
    json
    md
    mov
    mp3
    mp4
    pbix
    pdf
    png
    ppt
    pptx
    rar
    rar
    rst
    tsv
    txt
    wav
    wmv
    xls
    xlsx
    zip
)

for extension in "${extensions[@]}"
do
    find . -type f -iname "*.$extension" -exec chmod -x {} \;
done
