#!/bin/bash

LOGDIR="$HOME"/.log
LOGFILE="$LOGDIR"/autofs.log
LOGTIME="[$(date +"%d %b; %H:%M:%S")]"

if ! [[ -e "$LOGDIR" ]]; then
  mkdir -p "$LOGDIR"
fi

SHARES=$(find /media/autofs/ -mindepth 1 -maxdepth 1 -type d)

if [[ $SHARES ]]; then
  for d in $SHARES ; do
    if [[ -e ~/$(basename $d) ]]; then
      unlink ~/$(basename $d)
    fi
  done
  sudo /etc/rc.d/autofs stop >> "$LOGFILE"
fi

exit 0

# If you are going to use this script in a non-interactive environment, make
# sure that you are in the sudoers list or you are explicitly supplying your
# password to sudo in the script itself. Please refer to sudo man page to see
# how to do this.
