#!/bin/bash

BGCOLOR="$1"
FGCOLOR="$2"
if [[ -z "$BGCOLOR" ]]; then
  BGCOLOR="d7d7d7"
fi
if [[ -z "$FGCOLOR" ]]; then
  FGCOLOR="000000"
fi
gsettings set org.gnome.desktop.interface gtk-color-scheme \
  "selected_fg_color:#$FGCOLOR;selected_bg_color:#$BGCOLOR"

exit 0
