#!/bin/bash

gvfs-mime --set application/pdf mupdf.desktop
gvfs-mime --set application/ps evince.desktop

gvfs-mime --set inode/directory nemo.desktop

gvfs-mime --set text/csv libreoffice-calc.desktop
gvfs-mime --set text/tab-separated-values libreoffice-calc.desktop

gvfs-mime --set text/plain emacs.desktop
gvfs-mime --set text/x-c emacs.desktop
gvfs-mime --set text/x-python emacs.desktop
gvfs-mime --set text/x-r-source emacs.desktop
gvfs-mime --set text/richtext emacs.desktop
gvfs-mime --set text/tab-separated-value emacs.desktop
gvfs-mime --set text/x-vcard emacs.desktop
gvfs-mime --set text/x-vcalendar emacs.desktop
gvfs-mime --set text/english emacs.desktop
gvfs-mime --set text/rtf libreoffice-writer.desktop
gvfs-mime --set text/x-c++src emacs.desktop
gvfs-mime --set text/x-bibtex emacs.desktop
gvfs-mime --set text/x-crontab emacs.desktop
gvfs-mime --set text/x-csh emacs.desktop
gvfs-mime --set text/x-csrc emacs.desktop
gvfs-mime --set text/x-diff emacs.desktop
gvfs-mime --set text/x-java emacs.desktop
gvfs-mime --set text/x-makefile emacs.desktop
gvfs-mime --set text/x-perl emacs.desktop
gvfs-mime --set text/x-python emacs.desktop
gvfs-mime --set text/x-sh emacs.desktop
gvfs-mime --set text/x-tex emacs.desktop

gvfs-mime --set video/x-msvideo mpv.desktop
gvfs-mime --set video/quicktime mpv.desktop
gvfs-mime --set video/mpeg mpv.desktop
gvfs-mime --set video/3gpp mpv.desktop
gvfs-mime --set video/mp4 mpv.desktop
gvfs-mime --set video/webm mpv.desktop
gvfs-mime --set video/x-flv mpv.desktop
gvfs-mime --set video/x-ms-wm mpv.desktop
gvfs-mime --set video/x-ms-wmv mpv.desktop
gvfs-mime --set video/x-matroska mpv.desktop
gvfs-mime --set video/x-sgi-movie mpv.desktop

gvfs-mime --set audio/amr mpv.desktop
gvfs-mime --set audio/midi mpv.desktop
gvfs-mime --set audio/mpeg mpv.desktop
gvfs-mime --set audio/ogg mpv.desktop
gvfs-mime --set audio/x-ms-wma mpv.desktop
gvfs-mime --set audio/x-ms-wax mpv.desktop
gvfs-mime --set audio/x-pn-realaudio mpv.desktop
gvfs-mime --set audio/x-realaudio mpv.desktop
gvfs-mime --set audio/x-wav mpv.desktop

gvfs-mime --set image/gif eog.desktop
gvfs-mime --set image/jpeg eog.desktop
gvfs-mime --set image/png eog.desktop
gvfs-mime --set image/svg+xml eog.desktop
gvfs-mime --set image/tiff eog.desktop
gvfs-mime --set image/x-ms-bmp eog.desktop

exit 0
