#!/bin/bash

OIFS=$IFS
IFS=$'\n'

sudo updatedb

FILES=$(locate -i {~$,thumbs.db,.sw{p,o,n}})

if [[ ! -z "$FILES" ]]; then
  rm -i $FILES
fi

IFS=$OIFS
unset OIFS

exit 0

# If you are going to use this script in a non-interactive environment, make
# sure that you are in the sudoers list or you are explicitly supplying your
# password to sudo in the script itself. Please refer to sudo man page to see
# how to do this.
