#!/bin/bash

extensions=(
    txt
    jpg
    jpeg
    png
    gif
    bmp
    pdf
    doc
    docx
    xls
    xlsx
    ppt
    pptx
    mp3
    wav
    mp4
    avi
    mov
    wmv
    zip
    rar
    7z
    iso
    pbix
    html
    md
    rst
)

for extension in "${extensions[@]}"
do
    find . -type f -iname "*.$extension" -exec chmod -x {} \;
done
