#!/bin/bash

echo "Please provide the following information for the vCard."

echo "Enter: First Name"
read First
echo
echo "Enter: Last Name"
read Last
echo
echo "Enter: Organization"
read ORG
echo
echo "Enter: Designation"
read Desig
echo
echo "Enter: Work Telephone(s)"
read Work
echo
echo "Enter: Cellphone"
read Cell
echo
echo "Enter: Email"
read Email
echo
echo "Enter: Website"
read Url
echo
echo "Enter: Address"
read Add
echo


echo "BEGIN:VCARD
VERSION:2.1
N:${First};${Last}
FN:${First} ${Last}
ORG:${ORG}
TITLE:${Desig}
TEL;WORK;VOICE:${Work}
TEL;CELL;VOICE:${Cell}
EMAIL;PREF;INTERNET:${Email}
URL;WORK:${Url}
ADR;WORK;PREF:;;;${Add};;;
END:VCARD" > $HOME/tmp/"${First} ${Last}".vcf

