#!/bin/bash

# TODO: Seperate the pathname and filename so that the script can work on files
# in any directory instead of only files in the working directory.

for d in $*
do
  FILE=$(basename "$d" $(getext "$d"))
  ffmpeg -i "$d" -ab 192k -ar 44100 -ac 2 "$FILE".mp3
done

exit 0
