#!/bin/bash

if [[ -z $1 ]]; then
  amixer get Master | tail -2
fi

if [[ -z "$2" ]]; then
  INC=5
else
  INC="$2"
fi

mset () {
  amixer set Master "$1"% | tail -2
}

CURRENT=$(amixer scontents | grep % | head -1 | cut -f 2 -d [ | cut -f 1 -d '%')

if [[ "$1" == "--toggle-mute" || "$1" == "-t" ]]; then
  if [[ "$CURRENT" -gt 0 ]]; then
    echo $CURRENT > /tmp/volume.txt
    NEW=0
  else
    NEW=$(cat /tmp/volume.txt)
  fi
  mset "$NEW"
fi

if [[ "$1" == "--mute" || "$1" == "-m" ]]; then
  echo $CURRENT > /tmp/volume.txt
  NEW=0
  mset "$NEW"
fi

if [[ "$1" == "--unmute" || "$1" == "-n" ]]; then
  if [[ -e /tmp/volume.txt ]]; then
    LAST=$(cat /tmp/volume.txt)
  else
    LAST=50
  fi
  NEW="$LAST"
  mset "$NEW"
fi

if [[ "$1" == "--up" || "$1" == "-u" ]]; then
  NEW=$((CURRENT + INC))
  mset "$NEW"
fi

if [[ "$1" == "--down" || "$1" == "-d" ]]; then
  NEW=$((CURRENT - INC))
  mset "$NEW"
fi

exit 0
